### ISSUE TITLE
Version 11.0.2 returning error response

### ISSUE THREAD

**Issue by zardojunior** [Vantiv/litle-sdk-for-java#53]
Hi all.
After upgrading to 11.0.2 I got error responses for all requests that was successfull with version 9.12.2:

`<?xml version="1.0" encoding="UTF-8"?>
<litleOnlineResponse xmlns="http://www.litle.com/schema" version="11.1" response="1" message="System Error - Call Vantiv" />`

Any ideas?
Besides that, is the response version="11.1" correct?

**Comment by brianarnold789** [comment]
Hi @zardojunior,
If you are already setup to use XML v9.x you will need to reach out to you Vantiv eCommerce contact to get a different set of credentials for using XML v11.x.
For the response, since there is a credential error, the response XML is just returning as the latest version, it is not indicative of the request or schema validation.

**Comment by zardojunior** [comment]
Thank you.
Please close the issue ;-)

Em 1 de ago de 2017 11:45 AM, "brianarnold789" <notifications@github.com>
escreveu:

**Comment by zardojunior** [comment]
Should it work with sandbox?

2017-08-01 12:03 GMT-03:00 brianarnold789 <notifications@github.com>:

**Comment by VantivSDK** [comment]
Yes, you should be able to send XML v11.x transactions to the Sandbox environment successfully.
For these type of questions sdksupport@vaitiv.com is a better forum.
